
@catalogRuleId = catalogRuleId
@catalogId = catalogId


### Get all rules
GET {{pcmUrl}}/catalogs/rules 
#	?page[offset]=0
#	&page[limit]=10
accept: application/json
content-type: application/json



### Get rule by id
GET {{pcmUrl}}/catalogs/rules/{{catalogRuleId}} 
accept: application/json
content-type: application/json



### Create rule
POST {{pcmUrl}}/catalogs/rules 
accept: application/json
content-type: application/json

# EP-Channel: web
# EP-Context-Tag: vip

{
  "data": {
    "type": "catalog_rule",
    "attributes": {
      "name": "Preferred Customers",
      "description": "Preferred Customers",
      "catalog_id": "{{catalogId}}",
      "customer_ids": [],
      "tags": [],
      "channels": []
    }
  }
}
### Update rule
PUT {{pcmUrl}}/catalogs/rules/{{catalogRuleId}} 
accept: application/json
content-type: application/json


{
  "data": {
    "id": "{{catalogRuleId}}",
    "type": "catalog_rule",
    "attributes": {
      "name": "VIP Customers",
      "description": "VIP Customers",
      "catalog_id": "{{catalogId}}",
      "customer_ids": [],
      "tags": [],
      "channels": []
    }
  }
}
### Delete rule
DELETE {{pcmUrl}}/catalogs/rules/{{catalogRuleId}} 
accept: application/json
content-type: application/json



