
@customerID = customerID
@customerAddressId = customerAddressId


### Get customer addresses
GET {{baseUrl}}/customers/{{customerID}}/addresses 
#	?page[offset]=0
#	&page[limit]=10
accept: application/json
content-type: application/json



### Get customer address
GET {{baseUrl}}/customers/{{customerID}}/addresses/{{customerAddressId}} 
accept: application/json
content-type: application/json



### Create an address
POST {{baseUrl}}/customers/{{customerID}}/addresses 
accept: application/json
content-type: application/json


{
  "data": {
    "type": "address",
    "first_name": "Ron",
    "last_name": "Swanson",
    "name": "Home",
    "phone_number": "(555) 555-1234",
    "instructions": "Leave behind bin",
    "company_name": "Ron Swanson Enterprises",
    "line_1": "1 Sunny Street",
    "line_2": "",
    "city": "Sunny Town",
    "county": "Sunnyville",
    "postcode": "SU33 1YY",
    "country": "GB"
  }
}
### Update an address
PUT {{baseUrl}}/customers/{{customerID}}/addresses/{{customerAddressId}} 
accept: application/json
content-type: application/json


{
  "data": {
    "id": "{{customerAddressId}}",
    "type": "address",
    "name": "Home",
    "first_name": "Ron",
    "last_name": "Swanson",
    "line_1": "1 Sunny Street",
    "county": "Sunnyville",
    "postcode": "SU33 1YY",
    "country": "GB"
  }
}
### Delete an address
DELETE {{baseUrl}}/customers/{{customerID}}/addresses/{{customerAddressId}} 
accept: application/json
content-type: application/json



