
@hierarchyId = hierarchyId


### Get all hierarchies
GET {{pcmUrl}}/hierarchies 
#	?page[offset]=0
#	&page[limit]=10
accept: application/json
content-type: application/json



### Get a hierarchy by id
GET {{pcmUrl}}/hierarchies/{{hierarchyId}} 
accept: application/json
content-type: application/json



### Create a hierarchy
POST {{pcmUrl}}/hierarchies 
accept: application/json
content-type: application/json


{
  "data": {
    "type": "hierarchy",
    "attributes": {
      "name": "Games",
      "description": "All the games we sell",
      "slug": "games"
    }
  }
}
### Update a hierarchy
PUT {{pcmUrl}}/hierarchies/{{hierarchyId}} 
accept: application/json
content-type: application/json


{
  "data": {
    "id": "{{hierarchyId}}",
    "type": "hierarchy",
    "attributes": {
      "name": "Games for Kids",
      "description": "All the games we sell for kids",
      "slug": "games-kids"
    }
  }
}
### Delete a hierarchy
DELETE {{pcmUrl}}/hierarchies/{{hierarchyId}} 
accept: application/json
content-type: application/json



### Get a hierarchy's child nodes
GET {{pcmUrl}}/hierarchies/{{hierarchyId}}/children 
#	?page[offset]=0
#	&page[limit]=10
accept: application/json
content-type: application/json



