
@authenticationRealmId = authenticationRealmId
@passwordProfileId = passwordProfileId


### Get Password profiles
GET {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/password-profiles 
accept: application/json
content-type: application/json



### Get Password profile
GET {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/password-profiles/{{passwordProfileId}} 
accept: application/json
content-type: application/json



### Create Password profile
POST {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/password-profiles/ 
accept: application/json
content-type: application/json


{
  "data": {
    "usernameFormat": "email",
    "type": "password_profile",
    "name": "password profile"
  }
}
### Update Password profile
PUT {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/password-profiles/{{passwordProfileId}} 
accept: application/json
content-type: application/json


{
  "data": {
    "usernameFormat": "any",
    "type": "password_profile",
    "name": "updated password profile"
  }
}
### Delete Password profile
DELETE {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/password-profiles/{{passwordProfileId}} 
accept: application/json
content-type: application/json



