
@authenticationRealmId = authenticationRealmId
@userAuthenticationInfoId = userAuthenticationInfoId
@userAuthenticationOIDCProfileInfoId = userAuthenticationOIDCProfileInfoId
@oidcProfileIssuer = oidcProfileIssuer
@oidcProfileId = oidcProfileId


### Get all user authentication OIDC profile info
GET {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-oidc-profile-info 
accept: application/json
content-type: application/json



### Get user authentication OIDC profile info
GET {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-oidc-profile-info/{{userAuthenticationOIDCProfileInfoId}} 
accept: application/json
content-type: application/json



### Create user authentication OIDC profile info
POST {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-oidc-profile-info 
accept: application/json
content-type: application/json


{
  "data": {
    "type": "user_authentication_oidc_profile_info",
    "subject": "Test Subject",
    "issuer": "{{oidcProfileIssuer}}",
    "oidc_profile_id": "{{oidcProfileId}}"
  }
}
### Update user authentication OIDC profile info
PUT {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-oidc-profile-info/{{userAuthenticationOIDCProfileInfoId}} 
accept: application/json
content-type: application/json


{
  "data": {
    "type": "user_authentication_oidc_profile_info",
    "subject": "Test Subject Updated",
    "issuer": "{{oidcProfileIssuer}}"
  }
}
### Delete user authentication OIDC profile info
DELETE {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-oidc-profile-info/{{userAuthenticationOIDCProfileInfoId}} 
accept: application/json
content-type: application/json



