
@authenticationRealmId = authenticationRealmId
@userAuthenticationInfoId = userAuthenticationInfoId
@userAuthenticationPasswordProfileId = userAuthenticationPasswordProfileId
@passwordProfileId = passwordProfileId


### Get User Authentication Password Profiles
GET {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-password-profile-info 
accept: application/json
content-type: application/json



### Get User Authentication Password Profile
GET {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-password-profile-info/{{userAuthenticationPasswordProfileId}} 
accept: application/json
content-type: application/json



### Create User Authentication Password Profile
POST {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-password-profile-info 
accept: application/json
content-type: application/json


{
  "data": {
    "type": "user_authentication_password_profile_info",
    "password_profile_id": "{{passwordProfileId}}",
    "username": "john.doe",
    "password": "password"
  }
}
### Update User Authentication Password Profile
PUT {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-password-profile-info/{{userAuthenticationPasswordProfileId}} 
accept: application/json
content-type: application/json


{
  "data": {
    "id": "{{userAuthenticationPasswordProfileId}}",
    "type": "user_authentication_password_profile_info",
    "username": "john.doe",
    "password": "password.new"
  }
}
### Delete User Authentication Password profile
DELETE {{baseUrl}}/authentication-realms/{{authenticationRealmId}}/user-authentication-info/{{userAuthenticationInfoId}}/user-authentication-password-profile-info/{{userAuthenticationPasswordProfileId}} 
accept: application/json
content-type: application/json



